services:
  db:
    image: postgres:17-alpine3.21
    container_name: bloc3_db_jo2024
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "6000:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: back_jo2024
    ports:
      - "8081:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ID_GOOGLE: ${ID_GOOGLE}
      MDP_GOOGLE: ${MDP_GOOGLE}
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
