services:
  db:
    image: postgres:17-alpine
    container_name: db_jo2024
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "6000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - jo_network

  backend:
    build:
      context: ./backend
    container_name: back_jo2024
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ID_GOOGLE: ${ID_GOOGLE}
      MDP_GOOGLE: ${MDP_GOOGLE}
    depends_on:
      - db
    networks:
      - jo_network

  frontend:
    build:
      context: ./frontend
    container_name: front_jo2024
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - jo_network

volumes:
  db_data:

networks:
  jo_network:

