spring:
  application:
    name: jo2024

  datasource:
    url: jdbc:postgresql://${ALWAYS_POSTGRES_HOST}:${ALWAYS_POSTGRES_PORT}/${ALWAYS_POSTGRES_DB}
    username: ${ALWAYS_POSTGRES_USER}
    password: ${ALWAYS_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:5}
      minimum-idle: ${HIKARI_MIN_IDLE:2}
      pool-name: Jo2024ProdHikariPool

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false} # Pour éviter des logs excessifs.
    open-in-view: false
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: ${PORT:8080}

  # Compression des réponses HTTP pour la performance
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,image/svg+xml
    min-response-size: 1024 # Taille minimale pour compresser (en octets)
  error:
    include-message: never

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  path:
    prefix: /management
  auth:
    path:
      prefix: /management/auth

app:
  frontend:
    confirmation-base-url: ${FRONTEND_URL_CONF}
    reset-password-base-url: ${FRONTEND_URL_RESET}
  email:
    # Sujet et contenu de l'e-mail pour le billet
    sujet:
      billet: Votre billet pour les Jeux Olympiques !
    contenu:
      billet: "Bonjour %s,<br><br>Merci pour votre achat ! Vous trouverez votre billet en pièce jointe.<br>Votre clé de billet unique est : <b>%s</b>.<br><br>À bientôt aux JO !"

logging:
  level:
    root: INFO                # Niveau de log par défaut.
    fr.studi: INFO            # Logs de l'application en INFO, sauf si un module spécifique nécessite DEBUG temporairement.
    org.springframework: WARN
    org.hibernate: WARN