spring:
  application:
    name: jo2024

  datasource:
    url: jdbc:postgresql://localhost:6000/jo2024_db
    username: postgres
    password: motdepasse
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  mail:
    # Configuration Spring Mail
    host: smtp.gmail.com
    port: 587
    username: makhloufistudi@gmail.com
    password: otgtnpvevcrdxdqk
    properties:
      mail:
        smtp:
            auth: true
            starttls:
              enable: true
              required: true
    protocol: smtp
jwt:
  secret: '?NFKlvnlavazmb32645bzlhoIHOHOIdfnlkanzv#gaz'
  expiration: 36000000

app:
  frontend:
    confirmation-base-url: http://localhost:80/confirm
    reset-password-base-url: http://localhost:80/reset-password
  email:
    # Sujet et contenu de l'e-mail pour le billet
    sujet:
      billet: Votre billet pour les Jeux Olympiques !
    contenu:
      billet: "Bonjour %s,<br><br>Merci pour votre achat ! Vous trouverez votre billet en pièce jointe.<br>Votre clé de billet unique est : <b>%s</b>.<br><br>À bientôt aux JO !"

admin:
  email: jose@studi.fr
  password: Jose2024

logging:
  level:
    org:
      springframework:
        security: DEBUG