spring:
  application:
    name: jo2024

  datasource:
    url: jdbc:postgresql://${ALWAYS_POSTGRES_HOST}:${ALWAYS_POSTGRES_PORT}/${ALWAYS_POSTGRES_DB}
    username: ${ALWAYS_POSTGRES_USER}
    password: ${ALWAYS_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
server:
  port: ${PORT:8080}
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  path:
    prefix: /management
  auth:
    path:
      prefix: /management/auth

app:
  frontend:
    confirmation-base-url: ${FRONTEND_URL_CONF}
    reset-password-base-url: ${FRONTEND_URL_RESET}
  email:
    # Sujet et contenu de l'e-mail pour le billet
    sujet:
      billet: Votre billet pour les Jeux Olympiques !
    contenu:
      billet: "Bonjour %s,<br><br>Merci pour votre achat ! Vous trouverez votre billet en pièce jointe.<br>Votre clé de billet unique est : <b>%s</b>.<br><br>À bientôt aux JO !"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG