spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${ID_GOOGLE}
            client-secret: ${MDP_GOOGLE}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

server:
  port: ${PORT:8080}
  error:
    include-message: always

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  path:
    prefix: /management
  auth:
    path:
      prefix: /management/auth
