#Configurations par défaut
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            scope: profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  expiration: ${JWT_EXPIRATION}

server:
  port: 8080
  error:
    include-message: always

admin:
  path:
    prefix: /management
  auth:
    path:
      prefix: /management/auth