name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: heroku

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK 21 for backend
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Check Java version
      - name: Check Java version
        run: java -version

      # 4. Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      # 5. Set up Heroku authentication
      - name: Set up Heroku auth
        run: |
          printf "machine api.heroku.com\n  login %s\n  password %s\nmachine git.heroku.com\n  login %s\n  password %s\n" \
            "${{ secrets.HEROKU_EMAIL }}" "${{ secrets.HEROKU_API_KEY }}" \
            "${{ secrets.HEROKU_EMAIL }}" "${{ secrets.HEROKU_API_KEY }}" \
          > ~/.netrc
          chmod 600 ~/.netrc
          heroku auth:whoami

      # 6. Set Heroku config vars
      - name: Set Backend Heroku config vars
        run: |
          heroku config:set SPRING_PROFILES_ACTIVE=docker \
            # ... toutes vos variables d'environnement ...
            --app ${{ secrets.HEROKU_APP_NAME_BE }}

      # 7. Build & Deploy Backend to Heroku
      - name: Build & Deploy Backend to Heroku
        run: |
          mvn clean install -DskipTests
          heroku stack:set container --app ${{ secrets.HEROKU_APP_NAME_BE }}
          heroku container:login
          docker build . --platform linux/amd64 \
            -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME_BE }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME_BE }}/web
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME_BE }}

      # 8. Show Backend Heroku logs
      - name: Show Backend Heroku logs
        run: heroku logs --app ${{ secrets.HEROKU_APP_NAME_BE }} --num 100

      # 9. Arrêter les dynos
      - name: Stop Heroku Dynos
        if: ${{ false }} # désactivé par défaut
        run: |
          heroku ps:scale web=0 --app ${{ secrets.HEROKU_APP_NAME_BE }}